# Computer Vision

Implementation:

- Face and object recognition

- Objects tracking

## Cascade

Train with face impages and not face images (For face recognition)

- Train with AdaBost

- Select pattern attributes

    - Apply those attributes on subpart of the image until find a part that have those.

    - attributes are color black and white on each pixel

# Face Recognition

In [39]:
import cv2 #opencv
import numpy as np

In [36]:
image = cv2.imread('workplace-1245776_1920.jpg')

In [10]:
#code to see the image. it opens on a pop-up window
cv2.imshow('test',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
#detector_face = cv2.CascadeClassifier('haarcascade_front_alface_default.xml')
detector_face = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

In [18]:
detector_face

< cv2.CascadeClassifier 000001A9C8FECF90>

In [12]:
# gray images process faster
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [13]:
cv2.imshow('test',image_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
detection = detector_face.detectMultiScale(image_gray)

In [21]:
detection # position of faces [position x axis, y axis, size of face/bounding box, ]

array([[1639,  159,  141,  141],
       [ 928,  488,  172,  172],
       [ 284,  263,  113,  113],
       [ 229,  509,  142,  142],
       [1148,  261,  129,  129],
       [ 103,  784,   56,   56],
       [  44,  919,   30,   30]])

In [22]:
len(detection)

7

7 faces

In [25]:
for (x,y,w,h) in detection: #w:widht and h:height
    cv2.rectangle(image,
                  pt1= (x,y),
                  pt2= (x+w,y+h),
                  color= (0,255,0),
                  thickness= 2) #(0,255,0) color green

In [26]:
cv2.imshow('test',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

model dectect two parts that are not faces (false positive), so I will adjust some paremeters

In [31]:
detection = detector_face.detectMultiScale(image_gray, 
                                           scaleFactor=1.3, #scaleFactor increase the size of image (zoom)
                                           minSize=(30,30)) 

In [32]:
detection

array([[1635,  156,  147,  147],
       [ 928,  491,  171,  171],
       [ 222,  507,  151,  151],
       [ 284,  262,  114,  114],
       [1149,  260,  129,  129]])

In [37]:
for (x,y,w,h) in detection: #w:widht and h:height
    cv2.rectangle(image,
                  pt1= (x,y),
                  pt2= (x+w,y+h),
                  color= (0,255,0),
                  thickness= 2) #(0,255,0) color green

In [38]:
cv2.imshow('test',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
del image, image_gray, detection, detector_face

# Body recognition

In [41]:
image = cv2.imread('pessoas.jpg')

In [42]:
cv2.imshow('test',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [44]:
cv2.imshow('test',image_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
detection = detector_face.detectMultiScale(image_gray)

In [48]:
detector_body = cv2.CascadeClassifier('fullbody.xml')

In [104]:
detection = detector_body.detectMultiScale(image_gray, 
                                           scaleFactor=1.1, #scaleFactor increase the size of image (zoom)
                                           minSize=(50,50)
                                           )

In [105]:
detection

array([[532, 103,  66, 133],
       [266,  80,  75, 151],
       [461,  60,  92, 184],
       [195,  47,  96, 192],
       [144, 100,  71, 142],
       [327,  69,  84, 169],
       [ 70,  57,  95, 189],
       [ 12,  66,  90, 180]])

In [106]:
image = cv2.imread('pessoas.jpg')
for (x,y,w,h) in detection: #w:widht and h:height
    cv2.rectangle(image,
                  pt1= (x,y),
                  pt2= (x+w,y+h),
                  color= (0,255,0),
                  thickness= 2) #(0,255,0) color green

In [107]:
cv2.imshow('test',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

For more recognition look for harcascade xml