# Random Forest with Regression

- Ensemble learning

- For regression uses the **mean**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

In [3]:
from sklearn.ensemble import RandomForestRegressor

# Health Care data

In [2]:
data_health = pd.read_csv("health_care2.csv")
x_health = data_health.iloc[:,0:1].values
y_health = data_health.iloc[:,1].values
x_health,y_health

(array([[18],
        [23],
        [28],
        [33],
        [38],
        [43],
        [48],
        [53],
        [58],
        [63]], dtype=int64),
 array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
        10100], dtype=int64))

In [4]:
reg_random_health = RandomForestRegressor(n_estimators=10)
reg_random_health.fit(x_health,y_health)

RandomForestRegressor(n_estimators=10)

In [6]:
reg_random_health.score(x_health,y_health)

0.9692902393221186

In [10]:
x_test_tree = np.arange(min(x_health),max(x_health),0.1)
x_test_tree

C:\Users\ville\AppData\Local\Temp\ipykernel_16700\2861014875.py:1: DeprecationWarning:

Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)



array([18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. ,
       19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1,
       20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1, 21.2,
       21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3,
       22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4,
       23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4, 24.5,
       24.6, 24.7, 24.8, 24.9, 25. , 25.1, 25.2, 25.3, 25.4, 25.5, 25.6,
       25.7, 25.8, 25.9, 26. , 26.1, 26.2, 26.3, 26.4, 26.5, 26.6, 26.7,
       26.8, 26.9, 27. , 27.1, 27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8,
       27.9, 28. , 28.1, 28.2, 28.3, 28.4, 28.5, 28.6, 28.7, 28.8, 28.9,
       29. , 29.1, 29.2, 29.3, 29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30. ,
       30.1, 30.2, 30.3, 30.4, 30.5, 30.6, 30.7, 30.8, 30.9, 31. , 31.1,
       31.2, 31.3, 31.4, 31.5, 31.6, 31.7, 31.8, 31.9, 32. , 32.1, 32.2,
       32.3, 32.4, 32.5, 32.6, 32.7, 32.8, 32.9, 33

In [13]:
plot = px.scatter(x = x_health.ravel(),
                  y = y_health)
plot.add_scatter(x = x_test_tree.ravel(),
                  y = reg_random_health.predict(x_test_tree.reshape(-1,1)),
                  name = "Regression")
plot.show()

In [14]:
reg_random_health.predict([[40]])

array([1321.])

# House Prices Data

In [15]:
data_house = pd.read_csv("house_prices.csv")
x_house = data_house.iloc[:,3:19].values
y_house = data_house.iloc[:,2].values #price

In [16]:
from sklearn.model_selection import train_test_split
x_house_train, x_house_test, y_house_train, y_house_test = train_test_split(x_house,y_house,
                                                                            test_size=0.3,
                                                                            random_state=0)

In [17]:
x_house_train.shape, x_house_test.shape, y_house_train.shape, y_house_test.shape

((15129, 16), (6484, 16), (15129,), (6484,))

In [18]:
reg_random_house = RandomForestRegressor(n_estimators=100)
reg_random_house.fit(x_house_train,y_house_train)

RandomForestRegressor()

In [19]:
reg_random_house.score(x_house_train,y_house_train)

0.9813864878202117

In [20]:
reg_random_house.score(x_house_test,y_house_test)

0.8841081447971181

In [21]:
prediction = reg_random_house.predict(x_house_test)
prediction

array([ 309700.72      , 1721562.        ,  534884.52      , ...,
        361283.92666667,  235171.49      ,  208675.65      ])

In [22]:
y_house_test

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [23]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error

In [24]:
mean_absolute_error(y_house_test,prediction)

67808.40847706441