# Neural network with Regression

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

In [9]:
from sklearn.preprocessing import StandardScaler

In [11]:
from sklearn.neural_network import MLPRegressor

# Health care data

In [7]:
data_health = pd.read_csv("health_care2.csv")
x_health = data_health.iloc[:,0:1].values
y_health = data_health.iloc[:,1].values
x_health,y_health

(array([[18],
        [23],
        [28],
        [33],
        [38],
        [43],
        [48],
        [53],
        [58],
        [63]], dtype=int64),
 array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
        10100], dtype=int64))

In [10]:
scaler_x = StandardScaler()
x_health_stand = scaler_x.fit_transform(x_health)
scaler_y = StandardScaler()
y_health_stand = scaler_y.fit_transform(y_health.reshape(-1,1))

In [14]:
reg_neural_health = MLPRegressor(max_iter=1000)
reg_neural_health.fit(x_health_stand,y_health_stand.ravel())

MLPRegressor(max_iter=1000)

In [15]:
reg_neural_health.score(x_health_stand,y_health_stand)

0.9598600620438402

In [19]:
y_health_stand

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [20]:
plot = px.scatter(x = x_health_stand.ravel(),
                  y = y_health_stand.ravel())
plot.add_scatter(x = x_health_stand.ravel(),
                  y = reg_neural_health.predict(x_health_stand.reshape(-1,1)),
                  name = "Regression")
plot.show()

In [22]:
new_data = scaler_x.transform([[40]])
new_data

array([[-0.03481553]])

In [25]:
reg_neural_health.predict(new_data)

array([-0.50941305])

In [26]:
scaler_y.inverse_transform([reg_neural_health.predict(new_data)])

array([[1085.03383752]])

# House prices data

In [27]:
data_house = pd.read_csv("house_prices.csv")
x_house = data_house.iloc[:,3:19].values
y_house = data_house.iloc[:,2].values #price

In [28]:
from sklearn.model_selection import train_test_split
x_house_train, x_house_test, y_house_train, y_house_test = train_test_split(x_house,y_house,
                                                                            test_size=0.3,
                                                                            random_state=0)

In [29]:
x_house_train.shape, x_house_test.shape, y_house_train.shape, y_house_test.shape

((15129, 16), (6484, 16), (15129,), (6484,))

In [30]:
scaler_x = StandardScaler()
x_house_train_stand = scaler_x.fit_transform(x_house_train)
x_house_test_stand = scaler_x.transform(x_house_test)
scaler_y = StandardScaler()
y_house_train_stand = scaler_y.fit_transform(y_house_train.reshape(-1,1))
y_house_test_stand = scaler_y.transform(y_house_test.reshape(-1,1))

In [31]:
x_house_train_stand, y_house_train_stand

(array([[ 0.67170039, -0.79711466, -0.74522967, ...,  1.03727271,
          1.17348387, -0.83797629],
        [-0.38696772, -0.79711466, -0.68028398, ...,  1.03727271,
          1.53476983, -0.95879989],
        [ 1.7303685 ,  0.82292131,  0.84593978, ..., -0.48008241,
          1.07108346,  0.78248142],
        ...,
        [-0.38696772,  0.17490692,  0.30472568, ..., -0.66741021,
         -1.25528083,  0.3986888 ],
        [ 0.67170039, -0.14910028,  0.31554996, ..., -1.43545415,
         -1.99443873, -0.46129094],
        [ 0.67170039,  0.17490692,  0.32637425, ..., -1.3043247 ,
          0.38168351,  0.66876509]]),
 array([[-0.38454326],
        [-0.3024967 ],
        [ 0.49062008],
        ...,
        [-0.29976181],
        [-0.35445952],
        [ 0.43564888]]))

In [35]:
#16 variables +1 neurons output /2 hidden = 8.5~~9
#16 -> 9 -> 9 -> 1
reg_neural_house = MLPRegressor(max_iter=1000, hidden_layer_sizes=(9,9))
reg_neural_house.fit(x_house_train_stand,y_house_train_stand.ravel())

MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=1000)

In [37]:
reg_neural_house.score(x_house_train_stand,y_house_train_stand)

0.8763551289611549

In [36]:
reg_neural_house.score(x_house_test_stand,y_house_test_stand)

0.8734540536758105

In [38]:
prediction = reg_neural_house.predict(x_house_test_stand)
prediction

array([-0.47356966,  4.54155731,  0.1512462 , ..., -0.63448824,
       -0.94385106, -0.79848629])

In [40]:
y_house_test_stand

array([[-0.66623646],
       [ 2.83715179],
       [ 0.05878167],
       ...,
       [-0.43924097],
       [-0.74554814],
       [-0.91511104]])

In [42]:
y_house_test_stand_inverse = scaler_y.inverse_transform(y_house_test_stand)
prediction_inverse = scaler_y.inverse_transform(prediction.reshape(-1,1))

In [43]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error
mean_absolute_error(y_house_test_stand_inverse,prediction_inverse)

79112.56682433601